### ISSUE TITLE
generator can't exit normally to create test result

### ISSUE THREAD

**Issue by jhao0117** [timeplus-io/chameleon#3]
running generator with attached neutron_race.json, when timeout hit, generator is hang and does not exit to create report.

INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/neutron.go:226 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronServer).QueryStream.func1() read message from websocket : value=9,time=2022-04-26T02:08:00.649Z,_tp_time=2022-04-26T02:08:00.652Z,_tp_index_time=1970-01-01T00:00:00Z
INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:90 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).observeLatency() observe latency -5.056944ms
INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/neutron.go:226 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronServer).QueryStream.func1() read message from websocket : _tp_index_time=1970-01-01T00:00:00Z,value=9,time=2022-04-26T02:08:01.176Z,_tp_time=2022-04-26T02:08:01.179Z
INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:90 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).observeLatency() observe latency -5.281755ms
INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/neutron.go:226 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronServer).QueryStream.func1() read message from websocket : _tp_index_time=1970-01-01T00:00:00Z,value=9,time=2022-04-26T02:08:01.258Z,_tp_time=2022-04-26T02:08:01.262Z
INFO[1015]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:90 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).observeLatency() observe latency -5.549451ms
INFO[1016]/home/ec2-user/chameleon/generator/plugins/neutron/neutron.go:226 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronServer).QueryStream.func1() read message from websocket : time=2022-04-26T02:08:01.542Z,_tp_time=2022-04-26T02:08:01.544Z,_tp_index_time=1970-01-01T00:00:00Z,value=9
INFO[1016]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:90 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).observeLatency() observe latency -4.279038ms
INFO[1016]/home/ec2-user/chameleon/generator/plugins/neutron/neutron.go:226 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronServer).QueryStream.func1() read message from websocket : time=2022-04-26T02:08:02.377Z,_tp_time=2022-04-26T02:08:02.38Z,_tp_index_time=1970-01-01T00:00:00Z,value=9
INFO[1016]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:90 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).observeLatency() observe latency -4.954033ms
INFO[1200]/home/ec2-user/chameleon/generator/job/job.go:191 github.com/timeplus-io/chameleon/generator/job.(*Job).Start() timeout and exit data generating
INFO[1200]/home/ec2-user/chameleon/generator/plugins/neutron/observer.go:167 github.com/timeplus-io/chameleon/generator/plugins/neutron.(*NeutronObserver).Stop() call neutron stop observing

**Comment by jovezhong** [comment]
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).
