### ISSUE TITLE
demoapp doesn't work in latest.timeplus.io

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/chameleon#34]
It appears that the streams/views are not created automatically

> time="2022-10-17 21:27:05.263 +0000" level=error msg="failed to ingest data into stream car_live_data: request failed with status code 500, response body {\"code\":500,\"message\":\"failed to ingest data to stream car_live_data: code: 60, message: Code: 60. DB::Exception: Stream default.car_live_data doesn't exist. (UNKNOWN_STREAM) (version 1.0.104)\"}" func="[github.com/timeplus-io/chameleon/cardemo/sink/timeplus.(*TimeplusStreamProducer).send.func1](http://github.com/timeplus-io/chameleon/cardemo/sink/timeplus.(*TimeplusStreamProducer).send.func1)" file="/build/sink/timeplus/producer.go:79"

**Comment by gangtao** [comment]
it is better not to run demoapp at the start and only run it after the api key is configured
 you can run docker logs --follow --since 10m demoapp  to check the lasted log since 10minutes to avoid the historical logs

**Comment by jovezhong** [comment]
working now
